print("hello world")
print("hello world")
print("hello ")
print("machine learning")
a = input("enter the number")
b = input("enter the number")
c = a + b 
print(c)
print("wwe")
print("tinepass")
print("akash kathole")
d = input("hello world")
print(d)